### PR TITLE
Use triggers instead of infinite loops for blinky

### PR DESCRIPTION
**Pull request by gballet**
As discussed in #29, here is a new version of blinky that uses `trigger` instead of manually setting the led on and off again.

### CODE REVIEW

**Comment by gballet** [comment]
Strange, travis is failing on mac with a gcc version issue. Is that known?

**Comment by fhunleth** [comment]
The Travis issue is this one: https://github.com/nerves-project/nerves_system_rpi/issues/5. I really hopeful that it will be fixed tomorrow.

**Comment by ghitchens** [comment]
Gentlemen, I absolutely agree this is the "proper" way to write blinky, and anyone who wants to blink LEDs in their app would be well advised to use triggers rather than sleep.    

The original intent of blinky wasn't to necessarily show the "correct" way to build something, however.  It was to show how easy it is to get something working in Elixir in a way that people could understand intuitively in about 10 seconds.   

The original blinky took the "brian-dead" approach to blinking LEDs on purpose.   It didn't ask people to understand the concepts of supervision.  The first version didn't even require anyone to understand processes, although we changed that to allow the prompt to appear after boot.  It also didn't require anyone to understand the concept of /sys/class/leds or triggers or the details therein.

The purpose was to get people to say "wow, I know how to do that on an arduino, and now I know how to do it using Elixir on Nerves"

Having said this, i'm torn, because another valid use of an example is intended to show the proper way to do things.    I think for Nerves to become valuable we'd like to introduce concepts like this through examples.

What about keeping the existing blinky and calling this something like blinky_proper, so people can not have to learn more concepts than absolutely necessary when exploring their first elixir app, but also we demonstrate proper use of /sys/class/leds?

If others unanimously feel there's nothing lost by introducing triggers in to the most basic example, I'd concede, but I think it might be better as a "proper" example rather than "the simplest thing to understand that does something visible".

Thoughts?

**Comment by GregMefford** [comment]
@ghitchens: I agree with your feeling that, while this isn't really any more code, it does introduce more 'magic' than we probably want to show as a minimalist code snippet.

In keeping with the naming convention, we could call this new example `hello_leds` and keep it separate from the original `blinky`. That way, we still have the `blinky` example to show a dead-simple Elixir script doing something in Nerves, but `hello_leds` shows you the right way to control LEDs using the features in the `Nerves.Leds` module. If it's specifically an example about controlling LEDs, it could also demonstrate any other LED-related features without fear of over-complicating what was intended to be as simple as possible.

**Comment by ghitchens** [comment]
Thanks, @gballet!   I think this is a better solution.   I am going to try to give the examples some organizational love next week.

**Comment by GregMefford** [comment]
@gballet Thanks for being such a good sport! Great work! :rocket:
Ooh, I like the new GitHub Rocket emoji more than the previous one!

**Pull request merged**
