### PR TITLE
Bump nerves_system_#{target} dependency to 0.12

### PR DESCRIPTION
**Pull request by othatbrian**
Per a Slack discussion this morning, the "nerves_system_#{target}" dependency should be updated in all examples from 0.11 to 0.12.

I'm not sure if the mix.lock should be part of the pull request or not; from what I can tell, it should be.

### CODE REVIEW

**Comment by fhunleth** [comment]
@GregMefford and @mobileoverlord - Could we switch to `>= 0.0.0` or something similar? This is always going to be a problem and it's very constraining to keep every nerves_system_ version number the same. Also, https://github.com/nerves-project/nerves/issues/109

**Comment by GregMefford** [comment]
For some additional context on this PR, @othatbrian reported in Slack about getting the following error when trying to `mix firmware` in the `blinky` example:

```
nerves$ mix firmware
Env
  MIX_TARGET:   rpi3
  MIX_ENV:      dev

** (FunctionClauseError) no function clause matching in String.replace_suffix/3
    (nerves_bootstrap) lib/mix/tasks/nerves/loadpaths.ex:16: Mix.Tasks.Nerves.Loadpaths.run/1
    (nerves_bootstrap) lib/mix/tasks/nerves/precompile.ex:14: Mix.Tasks.Nerves.Precompile.run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:326: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:259: Mix.Task.run/2
    (mix) lib/mix/tasks/deps.compile.ex:62: Mix.Tasks.Deps.Compile.compile/2
    (mix) lib/mix/tasks/deps.loadpaths.ex:83: Mix.Tasks.Deps.Loadpaths.deps_check/2
    (mix) lib/mix/tasks/deps.loadpaths.ex:27: Mix.Tasks.Deps.Loadpaths.run/1
```
Connor said that this is usually caused by a bad `nerves_system_*` dep and we should try bumping from `0.11.0` to `0.12.0`. Since it solved the problem, @othatbrian agreed to put this PR together.

I really appreciate @othatbrian taking the time to make this PR, and it is an improvement that solves the problem for the targets that we officially support on the examples (`rpi` family and `bbb`), so I think we should merge it.

I'll work on a subsequent PR that splits out each target we want to officially support for the examples and lists their most-recently-verified versions per https://github.com/nerves-project/nerves/issues/109.

Any other thoughts, @mobileoverlord?

**Comment by mobileoverlord** [comment]
I agree with @fhunleth and @GregMefford. We need to attack the root of the issue, but in the meantime we should bump to at least 0.12

**Comment by GregMefford** [comment]
Thanks again, @othatbrian! 🎈 🚀 ✨

**Pull request merged**
